import "./globals.css";
import { Inter, Roboto,Montserrat,Open_Sans } from 'next/font/google'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({ subsets: ['latin'],weight:['400'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
